CREATE TABLE skip_diving.sd_user (
  user_id BIGSERIAL,
  name CHARACTER VARYING,
  lastname CHARACTER VARYING,
  username CHARACTER VARYING UNIQUE NOT NULL,
  password CHARACTER VARYING NOT NULL,
  email CHARACTER VARYING UNIQUE NOT NULL
);